# Use Node.js LTS (Long Term Support) image as the base
FROM node:lts-alpine

# Set the working directory in the container
WORKDIR /app

# Install pnpm
# RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Build the SvelteKit application
RUN npm run build

# Expose the port the app runs on
EXPOSE 5173

# Start the application
CMD ["npm", "run", "preview" , "--", "--host", "0.0.0.0"]
